# Generated by Django 3.1.3 on 2020-11-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(max_length=100),
        ),
    ]
